server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true  # eureka? ??
    fetch-registry: true        # eureka ????? ???? ??? ????? ??????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka